/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Cesium: typeof import('@/utils/cesium')['Cesium']
  const clsx: typeof import('clsx')['default']
  const dayjs: typeof import('@/utils/pkg-transport')['dayjs']
  const globalConfig: typeof import('@/global/config')['default']
  const local: typeof import('localforage')
  const memo: typeof import('react')['memo']
  const useBoolean: typeof import('ahooks')['useBoolean']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useHref: typeof import('react-router')['useHref']
  const useInRouterContext: typeof import('react-router')['useInRouterContext']
  const useLocation: typeof import('react-router')['useLocation']
  const useMemo: typeof import('react')['useMemo']
  const useMemoizedFn: typeof import('ahooks')['useMemoizedFn']
  const useMutation: typeof import('@tanstack/react-query')['useMutation']
  const useNavigate: typeof import('react-router')['useNavigate']
  const useNavigationType: typeof import('react-router')['useNavigationType']
  const useOutlet: typeof import('react-router')['useOutlet']
  const useOutletContext: typeof import('react-router')['useOutletContext']
  const useParams: typeof import('react-router')['useParams']
  const useQuery: typeof import('@tanstack/react-query')['useQuery']
  const useQueryClient: typeof import('@tanstack/react-query')['useQueryClient']
  const useRef: typeof import('react')['useRef']
  const useResolvedPath: typeof import('react-router')['useResolvedPath']
  const useRoutes: typeof import('react-router')['useRoutes']
  const useState: typeof import('react')['useState']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FC, ReactNode } from 'react'
  import('react')
}
