user  nginx;
worker_processes  auto;

error_log  /home/jingansi/apps/logs/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /home/jingansi/apps/logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;
    gzip  on;
    gzip_buffers 32 4K;
    gzip_comp_level 6;
    gzip_min_length 200;
    gzip_types application/javascript text/plain text/css application/json application/xml text/javascript;
    gzip_vary on;

    ssl on;
    #ssl证书的pem文件路径
   # ssl_certificate  /usr/share/nginx/ssl/keystore.pem;
   ssl_certificate  /usr/share/nginx/ssl/9578351_jingqi.jing-an.com.pem;
    #ssl证书的key文件路径
   # ssl_certificate_key /usr/share/nginx/ssl/keystore.key;
   ssl_certificate_key /usr/share/nginx/ssl/9578351_jingqi.jing-an.com.key;

    resolver 169.254.25.10 valid=10s ipv6=off;
    resolver_timeout 3s;
    
    upstream ja4anodeService{
        server ja-4a-node.ja.svc.cluster.local:7001 resolve  max_fails=1 fail_timeout=10s;
    }

    upstream ja4aGoService {
        server ja-4a-go.ja.svc.cluster.local:7001 resolve  max_fails=1 fail_timeout=10s;
    }

    upstream jingqiService{
       server ja-chingchi-icos.ja.svc.cluster.local:8081 resolve  max_fails=1 fail_timeout=10s;
    }

    server {
        listen  7003;
        server_name  127.0.0.1;
        location / {
            root /home/jingansi/apps/html;
            index index.html index.htm;
            try_files $uri /index.html;
        }
       
        
        location /api/ {
            proxy_pass http://ja4aGoService/;
            # proxy_pass http://172.21.30.201:9080/otherService/wanglou;
        }

        location /ws {
            proxy_pass http://jingqiService/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 600s;
        }

        # location /signaling {
        #     proxy_pass http://fly.jing-an.com:8444/signaling
        #     proxy_http_version 1.1;
        #     proxy_set_header Upgrade $http_upgrade;
        #     proxy_set_header Connection "upgrade";
        # }
      

    }

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
