export enum RightModeEnum {
  SET_POINT = 'setPoint',
  DRAW_POLYGON = 'drawPolygon',
  RANGING = 'ranging',
  SHOW_LAYER = 'showMapLayer',
  POINT_DETAIL = 'pointDetail',
  MARKER_DETAIL = 'markerDetail',
  POLYGON_DETAIL = 'polygonDetail',
  CIRCLE_DETAIL = 'circleDetail',
  HIDE = 'hide',
  EVENT_DETAIL = 'eventDetail',
  DEVICE = 'device',
  TASK_POINT_DETAIL = 'taskPointDetail',
  SHOW_CHAT = 'showChat',
  MARKER_LIST_DETAIL = 'markerListDetail',
  SITE = 'site',
  SITE_SATELLITE = 'siteSatellite',
  ROUTE = 'ROUTE',
  RADAR_TARGET = 'radarTarget',
  DRAW_SHAPE = 'drawShape',
  DRAW_GEOMETRY = 'drawGeometry',
}
