export const RIGHT_TOOLBAR_RIGHT = 12
export const RIGHT_PANEL_RIGHT = 54
export const RIGHT_OUTER_PANEL_WIDTH = 424
export const RIGHT_PANEL_GAP = 12
export const RIGHT_BOTTOM_BAR_HEIGHT = 20

export const RIGHT_TOOLBAR_SHIFT_WITH_OUTER =
  RIGHT_OUTER_PANEL_WIDTH + RIGHT_PANEL_GAP

export const RIGHT_PANEL_SHIFT_WITH_OUTER =
  RIGHT_TOOLBAR_SHIFT_WITH_OUTER + RIGHT_PANEL_RIGHT - RIGHT_TOOLBAR_RIGHT
